
SELECT * FROM USUARIO;
-- CREACION DE PROCEDIMIENTO

CREATE OR REPLACE
PROCEDURE EJEMPLO_CURSOR(   CUR_USERS OUT SYS_REFCURSOR) AS 
BEGIN 
  OPEN CUR_USERS FOR
    SELECT 
    APELLIDO_MATERNO, 
    CORREO,
    DIRECCION
    FROM   USUARIO;
END EJEMPLO_CURSOR;
-- ACTIVANDO TEXTO DE SALIDA
SET SERVEROUTPUT ON SIZE 1000000

-- EJECUCION DEL PROCEDIMIENTO
DECLARE
  l_cursor  SYS_REFCURSOR;
  APELLIDO_MATERNO VARCHAR2(250);
  CORREO VARCHAR2(250);
  DIRECCION VARCHAR2(250);

BEGIN
  EJEMPLO_CURSOR (l_cursor);
            
  LOOP 
    FETCH l_cursor
    INTO  APELLIDO_MATERNO, CORREO, DIRECCION;
    EXIT WHEN l_cursor%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(APELLIDO_MATERNO || ' | ' || CORREO || ' | ' || DIRECCION);
  END LOOP;
  CLOSE l_cursor;
END;