
CREATE OR REPLACE FUNCTION FN_VALID_CONTRACT
(   
    FIRMAS_IN  VARCHAR2,
    DESCRIPCION_IN  VARCHAR2
)
RETURN NUMBER AS
    INVALID_MODEL_USER EXCEPTION;
    IS_VALID_MODEL_USER EXCEPTION;
    STATUS_RESULT NUMBER;
BEGIN
    IF 
    FIRMAS_IN IS NULL OR FIRMAS_IN = '' OR
    DESCRIPCION_IN IS NULL OR DESCRIPCION_IN = ''
    THEN
        RAISE INVALID_MODEL_USER;
    ELSE
       RAISE IS_VALID_MODEL_USER;
    END IF;
    
--Declaración de Sentencia
    RETURN STATUS_RESULT;
EXCEPTION
    WHEN INVALID_MODEL_USER THEN
         STATUS_RESULT:=0;
         RETURN STATUS_RESULT;
    WHEN IS_VALID_MODEL_USER THEN
         STATUS_RESULT:=1;
         RETURN STATUS_RESULT;
    WHEN OTHERS THEN
        STATUS_RESULT:=-1;
        RETURN STATUS_RESULT;
        DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR EN LA FUNCTION ');
--Sentencias de control de excepción
END FN_VALID_CONTRACT;
