create or replace PROCEDURE FV_ADM_UPDATE_BALANCE
 (
    ID_SALDO_IN IN NUMBER,
    ID_FRUTA_IN IN NUMBER,
    ID_CALIDAD_IN IN NUMBER,
    ID_CLIENTE_COMPRADOR_IN IN NUMBER,
    DISPONIBLE_IN IN CHAR,
    KILOS_IN IN NUMBER,
    PRECIO_IN IN NUMBER,
    STATUS_RESULT_OUT OUT NUMBER
)

AS 
    COUNT_BALANCE NUMBER :=0;
    COUNT_USER NUMBER :=0;
    COUNT_FRUIT NUMBER :=0;
    COUNT_QUALITY NUMBER :=0;
    
    INVALID_USER EXCEPTION;
    INVALID_FRUIT EXCEPTION;
    INVALID_QUALITY EXCEPTION;
    INVALID_AVAILABILITY EXCEPTION;
    BALANCE_NOT_FOUND EXCEPTION;

    BALANCE_UPDATED EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO COUNT_BALANCE FROM SALDO WHERE ID_SALDO = ID_SALDO_IN;
    IF COUNT_BALANCE = 0 THEN
            RAISE BALANCE_NOT_FOUND;
    END IF;
    IF ID_CLIENTE_COMPRADOR_IN IS NOT NULL THEN 
        SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE ID_USUARIO = ID_CLIENTE_COMPRADOR_IN;
        IF COUNT_USER = 0 THEN
                RAISE INVALID_USER;
        END IF;
    END IF;

    IF ID_FRUTA_IN IS NOT NULL THEN 
        SELECT COUNT(*) INTO COUNT_FRUIT FROM FRUTA WHERE ID_FRUTA = ID_FRUTA_IN;
        IF COUNT_FRUIT = 0 THEN
            RAISE INVALID_FRUIT;
        END IF;
    END IF;
    
    IF ID_CALIDAD_IN IS NOT NULL THEN 
        SELECT COUNT(*) INTO COUNT_QUALITY FROM CALIDAD WHERE ID_CALIDAD = ID_CALIDAD_IN;
        IF COUNT_QUALITY = 0 THEN
            RAISE INVALID_QUALITY;
        END IF;
    END IF;

    IF DISPONIBLE_IN IS NOT NULL THEN 
        IF DISPONIBLE_IN NOT BETWEEN 0 AND 1  THEN
            RAISE INVALID_AVAILABILITY;
        END IF;
    END IF;
    
    UPDATE SALDO 
    SET
    ID_FRUTA = COALESCE(ID_FRUTA_IN, ID_FRUTA), 
    ID_CALIDAD = COALESCE(ID_CALIDAD_IN, ID_CALIDAD), 
    ID_CLIENTE_COMPRADOR = COALESCE(ID_CLIENTE_COMPRADOR_IN, ID_CLIENTE_COMPRADOR), 
    DISPONIBLE = COALESCE(DISPONIBLE_IN, DISPONIBLE), 
    KILOS = COALESCE(KILOS_IN, KILOS),
    PRECIO = COALESCE(PRECIO_IN, PRECIO)
    WHERE ID_SALDO = ID_SALDO_IN;
    RAISE BALANCE_UPDATED;
    
    EXCEPTION
    WHEN BALANCE_UPDATED THEN
        STATUS_RESULT_OUT := 1;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('SALDO ACTUALIZADO' );
    WHEN INVALID_USER THEN
        STATUS_RESULT_OUT := 0;
        DBMS_OUTPUT.PUT_LINE('USUARIO INVALIDO' );
    WHEN INVALID_FRUIT THEN
        STATUS_RESULT_OUT := -1;
        DBMS_OUTPUT.PUT_LINE('FRUTA INVALIDA' );
    WHEN INVALID_QUALITY THEN
        STATUS_RESULT_OUT := -2;
        DBMS_OUTPUT.PUT_LINE('CALIDAD INVALIDA' );
    WHEN INVALID_AVAILABILITY THEN
        STATUS_RESULT_OUT := -3;
        DBMS_OUTPUT.PUT_LINE('DISPONIBILIDAD INVALIDA' );
    WHEN BALANCE_NOT_FOUND THEN
        STATUS_RESULT_OUT := -4;
        DBMS_OUTPUT.PUT_LINE('SALDO INVALIDO' );
    WHEN OTHERS THEN   
        STATUS_RESULT_OUT:= -5;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR EN EL PL' );
        
END;

-- DECLARE
--  STATUS_RESULT_OUT NUMBER;

-- BEGIN
--  FV_ADM_UPDATE_BALANCE(1,1, 1, 1, 1, 2000, STATUS_RESULT_OUT);
--      DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);

-- END;

    

