CREATE OR REPLACE
PROCEDURE FV_ADM_SELECT_USER_INIT_REQUEST
(
ID_ESTADO_SOLICITUD_IN IN NUMBER,
STATUS_RESULT_OUT OUT NUMBER,
CURSOR_RESULT_OUT OUT SYS_REFCURSOR
) 
AS 
INVALID_MODEL EXCEPTION;
APPLICATION_FOUND EXCEPTION;
MIN_ESTADO NUMBER := 0;
MAX_ESTADO NUMBER:= 0;
BEGIN 
    SELECT MIN(ID_ESTADO_SOLICITUD),  MAX(ID_ESTADO_SOLICITUD) INTO MIN_ESTADO, MAX_ESTADO  FROM ESTADO_SOLICITUD;

    IF ID_ESTADO_SOLICITUD_IN NOT BETWEEN MIN_ESTADO AND MAX_ESTADO THEN
        RAISE INVALID_MODEL;
    END IF;
    DBMS_OUTPUT.PUT_LINE('ID_ESTADO_SOLICITUD_IN: ' || ID_ESTADO_SOLICITUD_IN);
    OPEN CURSOR_RESULT_OUT FOR
        SELECT S.ID_SOLICITUD, COUNT(DT.ID_DETALLE_SOLICITUD) FROM SOLICITUD S 
        JOIN DETALLE_SOLICITUD DT ON(S.ID_SOLICITUD = DT.ID_SOLICITUD) 
        WHERE S.ID_ESTADO_SOLICITUD = ID_ESTADO_SOLICITUD_IN
        GROUP BY S.ID_SOLICITUD;

        RAISE APPLICATION_FOUND;
EXCEPTION
    WHEN APPLICATION_FOUND THEN
        STATUS_RESULT_OUT:= 1;
        DBMS_OUTPUT.PUT_LINE('SOLICITUDES ENCONTRADAS' );
    WHEN INVALID_MODEL THEN
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('ESTADO DE SOLICITUD INVALIDO' );
    WHEN OTHERS THEN
        STATUS_RESULT_OUT:= -2;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END FV_ADM_SELECT_USER_INIT_REQUEST;

-- EJECUCION DEL PL
SET SERVEROUTPUT ON;

-- DECLARE
--     CURSOR_TO_EACH  SYS_REFCURSOR;
--     STATUS_RESULT_OUT NUMBER;
--     ID_SOLICITUD NUMBER;
--     CANTIDAD_SOLICITUD NUMBER;
-- BEGIN
--   FV_ADM_SELECT_USER_INIT_REQUEST (9, STATUS_RESULT_OUT ,CURSOR_TO_EACH);
-- DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT EXTERIOR: ' || STATUS_RESULT_OUT);
--     IF CURSOR_TO_EACH%ISOPEN THEN      
--       LOOP 
--         FETCH CURSOR_TO_EACH
--         INTO  ID_SOLICITUD, CANTIDAD_SOLICITUD;
--         EXIT WHEN CURSOR_TO_EACH%NOTFOUND;
--         DBMS_OUTPUT.PUT_LINE(ID_SOLICITUD || ' | ' || CANTIDAD_SOLICITUD );
--       END LOOP;
--       CLOSE CURSOR_TO_EACH;
--     END IF;
-- END;
