create or replace PROCEDURE FV_ADM_CREATE_CONTRACT
 (
    DESCRIPCION_IN IN VARCHAR2,
    FIRMAS_IN IN VARCHAR2,
    ESTADO_CONTRATO_IN IN NUMBER,
    ID_RESULT_OUT OUT NUMBER,
    STATUS_RESULT_OUT OUT NUMBER
)

AS 
    IS_VALID_CONTRACT NUMBER := 0;
    FECHA_EMISION_VAR DATE;
    FECHA_EXPIRACION_VAR DATE;
    INVALID_MODEL EXCEPTION;
    CONTRACT_CREATED EXCEPTION;
    MIN_ESTADO NUMBER := 0;
    MAX_ESTADO NUMBER:= 0;
BEGIN
    SELECT MIN(ID_ESTADO_CONTRATO), MAX(ID_ESTADO_CONTRATO) INTO MIN_ESTADO, MAX_ESTADO FROM ESTADO_CONTRATO;
    IF ESTADO_CONTRATO_IN NOT BETWEEN MIN_ESTADO AND MAX_ESTADO THEN
            RAISE INVALID_MODEL;
    END IF;
    
    SELECT FN_VALID_CONTRACT(DESCRIPCION_IN, FIRMAS_IN) INTO IS_VALID_CONTRACT FROM DUAL;   
    IF IS_VALID_CONTRACT != 1 THEN
        DBMS_OUTPUT.PUT_LINE('HAY PROBLEMA CON LA FUNCION DEBIDO A QUE EL MODELO NO ESTA COMPLETO' );
        RAISE INVALID_MODEL;
    END IF;
--    
    FECHA_EMISION_VAR := SYSDATE;
    FECHA_EXPIRACION_VAR := SYSDATE+365;
    INSERT INTO CONTRATO (DESCRIPCION, FECHA_EMISION, FECHA_EXPIRACION, FIRMAS, ID_ESTADO_CONTRATO) VALUES (DESCRIPCION_IN, FECHA_EMISION_VAR, FECHA_EXPIRACION_VAR, FIRMAS_IN, ESTADO_CONTRATO_IN) RETURN ID_CONTRATO INTO ID_RESULT_OUT;
    RAISE CONTRACT_CREATED;
    
    EXCEPTION
    WHEN CONTRACT_CREATED THEN
        STATUS_RESULT_OUT := 1;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('CONTRATO CREADO' );
    WHEN INVALID_MODEL THEN
        STATUS_RESULT_OUT := 0;
        DBMS_OUTPUT.PUT_LINE('MODELO INGRESADO INVALIDO' );
    WHEN OTHERS THEN   
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
        
END;




    

-- DECLARE
-- STATUS_RESULT_OUT NUMBER;
-- ID_RESULT_OUT NUMBER;

-- BEGIN
--     FV_ADM_CREATE_CONTRACT('DESCRIPCION CONTRACT','1',1,ID_RESULT_OUT, STATUS_RESULT_OUT);
--     DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);
--         DBMS_OUTPUT.PUT_LINE('ID_RESULT_OUT: '||ID_RESULT_OUT);

-- END;