CREATE OR REPLACE PROCEDURE
    FV_ADM_UPDATE_REQUEST_STATE(
    ID_SOLICITUD_IN IN NUMBER,
    ID_ESTADO_SOLICITUD_IN IN NUMBER,
    STATUS_RESULT_OUT OUT NUMBER)

AS
    INVALID_MODEL EXCEPTION;
    REQUEST_NOT_FOUND EXCEPTION;
    REQUEST_STATE_UPDATED EXCEPTION;
    REQUEST_DELETE EXCEPTION;
    MIN_ESTADO NUMBER := 0;
    MAX_ESTADO NUMBER:= 0;
    COUNT_REQUEST NUMBER:= 0;

BEGIN

    SELECT COUNT(*) INTO COUNT_REQUEST FROM SOLICITUD WHERE ID_SOLICITUD = ID_SOLICITUD_IN;
    SELECT MIN(ID_ESTADO_SOLICITUD), MAX(ID_ESTADO_SOLICITUD) INTO MIN_ESTADO, MAX_ESTADO FROM ESTADO_SOLICITUD;
    
    IF COUNT_REQUEST = 0 THEN
        RAISE REQUEST_NOT_FOUND;
    END IF;
    
    
    IF COUNT_REQUEST > 0 THEN
        IF ID_ESTADO_SOLICITUD_IN NOT BETWEEN MIN_ESTADO AND MAX_ESTADO THEN
            RAISE INVALID_MODEL;
        ELSE
            UPDATE SOLICITUD SET ID_ESTADO_SOLICITUD = ID_ESTADO_SOLICITUD_IN WHERE ID_SOLICITUD = ID_SOLICITUD_IN;
            RAISE REQUEST_STATE_UPDATED;
        END IF;
    END IF;
    
    
    
EXCEPTION
    WHEN REQUEST_NOT_FOUND THEN
        STATUS_RESULT_OUT:= 0;
        DBMS_OUTPUT.PUT_LINE('SOLICITUD NO ENCONTRADA' );
    WHEN INVALID_MODEL THEN
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('MODELO INGRESADO INVALIDO' );
    WHEN REQUEST_STATE_UPDATED THEN
        STATUS_RESULT_OUT:= 1;
        DBMS_OUTPUT.PUT_LINE('ESTADO DE SOLICITUD ACTUALIZADO CORRECTAMENTE' );
    WHEN REQUEST_DELETE THEN
    STATUS_RESULT_OUT:= 2;
        DBMS_OUTPUT.PUT_LINE('ESTADO DE SOLICITUD ELIMINADO CORRECTAMENTE' );
    WHEN OTHERS THEN
        STATUS_RESULT_OUT:= -2;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END FV_ADM_UPDATE_REQUEST_STATE;


/*SET SERVEROUTPUT ON;   
DECLARE
STATUS_RESULT_OUT NUMBER;
BEGIN
    FV_ADM_UPDATE_REQUEST_STATE(2,2,STATUS_RESULT_OUT);
    DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);
END;*/