CREATE OR REPLACE 
PROCEDURE FV_TRA_DELETE_TRUCK(
ID_CAMION_IN IN NUMBER
,STATUS_RESULT_OUT OUT NUMBER)

AS
INVALID_MODEL EXCEPTION
;TRUCK_DELETED EXCEPTION
;TRUCK_NOT_FOUND EXCEPTION
;MIN_TYPE NUMBER := 0
;MAX_TYPE NUMBER:= 0
;COUNT_TRUCK NUMBER :=0
;
BEGIN

    IF ID_CAMION_IN NOT BETWEEN MIN_TYPE AND MAX_TYPE THEN
        RAISE INVALID_MODEL;
    END IF;
    DBMS_OUTPUT.PUT_LINE('ID_CAMION_IN: ' || ID_CAMION_IN);
    
    IF ID_CAMION_IN BETWEEN MIN_TYPE AND MAX_TYPE THEN 
            SELECT COUNT(*) INTO COUNT_TRUCK FROM CAMION WHERE ID_CAMION = ID_CAMION_IN;
            IF  COUNT_TRUCK = 0 THEN
                RAISE TRUCK_NOT_FOUND;
            ELSE
                DELETE FROM CAMION WHERE ID_CAMION = ID_CAMION_IN;
                RAISE TRUCK_DELETED;
            COMMIT;
            END IF;
    END IF;
        
    

EXCEPTION
    WHEN TRUCK_NOT_FOUND THEN
        STATUS_RESULT_OUT:= 0;
        DBMS_OUTPUT.PUT_LINE('CAMION NO ENCONTRADO' );
    WHEN INVALID_MODEL THEN
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('MODELO INGRESADO INVALIDO' );
    WHEN TRUCK_DELETED THEN
        STATUS_RESULT_OUT:= 1;
        DBMS_OUTPUT.PUT_LINE('CAMION ELIMINADO CORRECTAMENTE' );
    WHEN OTHERS THEN
        STATUS_RESULT_OUT:= -2;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END FV_TRA_DELETE_TRUCK;

/*SET SERVEROUTPUT ON;    

DECLARE
STATUS_RESULT_OUT NUMBER;
BEGIN
FV_TRA_DELETE_TRUCK(1,STATUS_RESULT_OUT);
DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);
END;
*/