CREATE OR REPLACE 
PROCEDURE FV_TRA_DELETE_TRUCK(
ID_CAMION_IN IN NUMBER
,STATUS_RESULT_OUT OUT NUMBER)

AS
INVALID_MODEL EXCEPTION
;TRUCK_DELETED EXCEPTION
;TRUCK_NOT_FOUND EXCEPTION
;MIN_ID NUMBER := 0
;MAX_ID NUMBER:= 0
;COUNT_TRUCK NUMBER :=0
;
BEGIN

    SELECT COUNT(*) INTO COUNT_TRUCK FROM CAMION WHERE ID_CAMION = ID_CAMION_IN;
    
    SELECT MIN(ID_CAMION), MAX(ID_CAMION) INTO MIN_ID, MAX_ID FROM CAMION;
    
    IF ID_CAMION_IN NOT BETWEEN MIN_ID AND MAX_ID THEN
        RAISE TRUCK_NOT_FOUND;
    END IF;
    DBMS_OUTPUT.PUT_LINE('ID_CAMION_IN: ' || ID_CAMION_IN);
    
        IF ID_CAMION_IN BETWEEN MIN_ID AND MAX_ID THEN
        DELETE FROM CAMION WHERE ID_CAMION = ID_CAMION_IN;
        RAISE TRUCK_DELETED;
        COMMIT;
        END IF;

EXCEPTION
    WHEN TRUCK_NOT_FOUND THEN
        STATUS_RESULT_OUT:= 0;
        DBMS_OUTPUT.PUT_LINE('CAMION NO ENCONTRADO' );
    WHEN TRUCK_DELETED THEN
        STATUS_RESULT_OUT:= 1;
        DBMS_OUTPUT.PUT_LINE('CAMION ELIMINADO CORRECTAMENTE' );
    WHEN OTHERS THEN
        STATUS_RESULT_OUT:= -2;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END FV_TRA_DELETE_TRUCK;

/*SET SERVEROUTPUT ON;    

DECLARE
STATUS_RESULT_OUT NUMBER;
BEGIN
FV_TRA_DELETE_TRUCK(2,STATUS_RESULT_OUT);
DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);
END;*/