-- SECUENCIA DE USUARIO - RANSPORTISTA Y PRODUCTOR

DROP SEQUENCE USUARIO_INCREMENTO;
CREATE SEQUENCE USUARIO_INCREMENTO
START WITH 1 
INCREMENT BY 1;

DROP SEQUENCE TRANSPORTISTA_INCREMENTO;
CREATE SEQUENCE TRANSPORTISTA_INCREMENTO
START WITH 1 
INCREMENT BY 1;

DROP SEQUENCE PRODUCTOR_INCREMENTO;
CREATE SEQUENCE PRODUCTOR_INCREMENTO
START WITH 1 
INCREMENT BY 1;

DROP SEQUENCE CONTRATO_INCREMENTO;
CREATE SEQUENCE CONTRATO_INCREMENTO
START WITH 1 
INCREMENT BY 1;

DROP SEQUENCE SOLICITUD_INCREMENTO;
CREATE SEQUENCE SOLICITUD_INCREMENTO
START WITH 1 
INCREMENT BY 1;

DROP SEQUENCE DETAILREQ_INCREMENTO;
CREATE SEQUENCE DETAILREQ_INCREMENTO
START WITH 1 
INCREMENT BY 1;

-- TRIIGER DE ID DE INCREMENTO DE USUARIO - RANSPORTISTA Y PRODUCTOR

CREATE OR REPLACE TRIGGER TRG_INCREMENTO_ID_USUARIO
BEFORE INSERT ON USUARIO 
FOR EACH ROW
BEGIN
    SELECT USUARIO_INCREMENTO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TRG_INCREMENTO_ID_TRANSPORTISTA
BEFORE INSERT ON TRANSPORTISTA 
FOR EACH ROW
BEGIN
    SELECT TRANSPORTISTA_INCREMENTO.NEXTVAL INTO :NEW.ID_TRANSPORTISTA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TRG_INCREMENTO_ID_PRODUCTOR
BEFORE INSERT ON PRODUCTOR 
FOR EACH ROW
BEGIN
    SELECT PRODUCTOR_INCREMENTO.NEXTVAL INTO :NEW.ID_PRODUCTOR FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TRG_INCREMENTO_ID_CONTRATO
BEFORE INSERT ON CONTRATO 
FOR EACH ROW
BEGIN
    SELECT CONTRATO_INCREMENTO.NEXTVAL INTO :NEW.ID_CONTRATO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TRG_INCREMENTO_ID_SOLICITUD
BEFORE INSERT ON SOLICITUD 
FOR EACH ROW
BEGIN
    SELECT SOLICITUD_INCREMENTO.NEXTVAL INTO :NEW.ID_SOLICITUD FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TRG_INCREMENTO_ID_DETAILREQ
BEFORE INSERT ON DETALLE_SOLICITUD 
FOR EACH ROW
BEGIN
    SELECT DETAILREQ_INCREMENTO.NEXTVAL INTO :NEW.ID_DETALLE_SOLICITUD FROM DUAL;
END;
