CREATE OR REPLACE TRIGGER TRG_AUCTION_CLOSE
BEFORE UPDATE OF CAMION_SELECCIONADO ON SUBASTA 
FOR EACH ROW
DECLARE 
BEGIN
    UPDATE SOLICITUD SET ID_ESTADO_SOLICITUD = 5 WHERE ID_SOLICITUD = :old.ID_SOLICITUD;
    INSERT INTO VENTA (ID_SOLICITUD, ID_ESTADO_VENTA, ID_TIPO_PAGO) VALUES (:old.ID_SOLICITUD, 1, null);
END;

