CREATE OR REPLACE TRIGGER TRG_CREATE_ROUTES
AFTER INSERT ON SUBASTA 
FOR EACH ROW
DECLARE 
  
    ID_RUTA_IN NUMBER := 0;
    ID_CLIENTE_IN NUMBER := 0;
    ID_PRODUCTOR_IN NUMBER := 0;
    DIRECCION_PRODUCTOR VARCHAR2(150);
    DIRECCION_CLIENTE VARCHAR2(150);
    ID_TIPO_CLIENTE_IN NUMBER := 0;




BEGIN

   
 
    INSERT INTO RUTA 
    (ID_SUBASTA ) VALUES 
    (:new.ID_SUBASTA ) RETURN  ID_RUTA INTO ID_RUTA_IN ; 
    
    
    SELECT 
    ID_USUARIO, PRODUCTOR_SELECCIONADO 
    INTO 
    ID_CLIENTE_IN, ID_PRODUCTOR_IN
    FROM SOLICITUD WHERE ID_SOLICITUD = :new.ID_SOLICITUD;
    
    SELECT DIRECCION INTO DIRECCION_PRODUCTOR FROM PRODUCTOR WHERE ID_PRODUCTOR = ID_PRODUCTOR_IN;

    SELECT ID_TIPO_USUARIO, DIRECCION INTO ID_TIPO_CLIENTE_IN, DIRECCION_CLIENTE FROM USUARIO WHERE ID_USUARIO = ID_CLIENTE_IN;
    
    INSERT INTO DETALLE_RUTA ( DIRECCION_PARTIDA, DIRECCION_DESTINO , ID_RUTA, OBSERVACION, FECHA_RETIRO) 
    VALUES (DIRECCION_PRODUCTOR, 'Bodega Central',  ID_RUTA_IN , NULL , SYSDATE + 1 );
    
    IF ID_TIPO_CLIENTE_IN = 2 THEN
        
        
        INSERT INTO DETALLE_RUTA ( DIRECCION_PARTIDA, DIRECCION_DESTINO , ID_RUTA, OBSERVACION, FECHA_RETIRO) 
        VALUES ('Bodega Central', 'Puerto' ,  ID_RUTA_IN , NULL , SYSDATE + 3 );

    ELSE
     
        INSERT INTO DETALLE_RUTA ( DIRECCION_PARTIDA, DIRECCION_DESTINO , ID_RUTA, OBSERVACION, FECHA_RETIRO) 
        VALUES ('Bodega Central', DIRECCION_CLIENTE ,  ID_RUTA_IN , NULL , SYSDATE + 3 );
    END IF;

END;


