create or replace PROCEDURE FV_LOGIN
 (
    CORREO_IN IN  VARCHAR2,
    CONTRASENA_IN IN  VARCHAR2,
    STATUS_OUT OUT NUMBER, 
    TIPO_USUARIO_OUT OUT VARCHAR2,
    ID_USUARIO_OUT OUT NUMBER
)

AS
    FOUND_USER EXCEPTION;
    COUNT_USER NUMBER := 0;

BEGIN
    
        
        SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
        IF  COUNT_USER > 0 THEN
            SELECT  TU.CATEGORIA, U.ID_USUARIO INTO TIPO_USUARIO_OUT, ID_USUARIO_OUT
            FROM USUARIO U JOIN TIPO_USUARIO TU ON (U.ID_TIPO_USUARIO = TU.ID_TIPO_USUARIO) 
            WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
            
            RAISE FOUND_USER;
            
        ELSE
            STATUS_OUT:= 0;
        END IF;
        
        SELECT COUNT(*) INTO COUNT_USER FROM PRODUCTOR 
        WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
        IF COUNT_USER > 0 THEN
            SELECT ID_PRODUCTOR INTO ID_USUARIO_OUT FROM PRODUCTOR 
            WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
            
            TIPO_USUARIO_OUT:= 'PRODUCTOR';
            RAISE FOUND_USER;   
        ELSE
            STATUS_OUT:= 0;
        END IF;

        
        SELECT COUNT(*) INTO COUNT_USER FROM TRANSPORTISTA 
        WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
        IF COUNT_USER > 0 THEN
            SELECT ID_TRANSPORTISTA INTO ID_USUARIO_OUT FROM TRANSPORTISTA 
            WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
            
            TIPO_USUARIO_OUT:= 'TRANSPORTISTA';
            RAISE FOUND_USER;
        ELSE
            STATUS_OUT:= 0;
        END IF;

EXCEPTION
    WHEN FOUND_USER THEN
        STATUS_OUT:= 1;
        DBMS_OUTPUT.PUT_LINE('SE ENCONTRO EL USUARIO' );
    WHEN OTHERS THEN
        STATUS_OUT:= 0;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
   
END;