CREATE OR REPLACE PROCEDURE
FV_PRO_REQUEST_PARTICIPATION
(
    ID_SOLICITUD_IN IN NUMBER,
    ID_PRODUCTOR_IN IN NUMBER,
    PRODUCTOR_PRICE_IN IN NUMBER,
    STATUS_RESULT_OUT OUT NUMBER
)

AS
PRODUCTOR_NOT_FOUND EXCEPTION;
REQUEST_NOT_FOUND EXCEPTION;
PRODUCTOR_PARTICIPATING EXCEPTION;
COUNT_SOLICITUD NUMBER := 0;
COUNT_PRODUCTOR NUMBER := 0;


BEGIN
    SELECT COUNT(*) INTO COUNT_PRODUCTOR FROM PRODUCTOR WHERE ID_PRODUCTOR = ID_PRODUCTOR_IN;
    SELECT COUNT(*) INTO COUNT_SOLICITUD FROM SOLICITUD WHERE ID_SOLICITUD = ID_SOLICITUD_IN AND PRODUCTOR_SELECCIONADO IS NULL;
    IF COUNT_PRODUCTOR = 0 THEN
        RAISE PRODUCTOR_NOT_FOUND;
    END IF;
    
    IF COUNT_SOLICITUD = 0 THEN
        RAISE REQUEST_NOT_FOUND;
    ELSE
        INSERT INTO PRODUCTOR_SOLICITUD(PRECIO, ID_SOLICITUD, ID_PRODUCTOR) VALUES (PRODUCTOR_PRICE_IN, ID_SOLICITUD_IN, ID_PRODUCTOR_IN);
        UPDATE SOLICITUD SET 
        PRODUCTOR_SELECCIONADO = ID_PRODUCTOR_IN,
        ID_ESTADO_SOLICITUD = 4 
        WHERE ID_SOLICITUD = ID_SOLICITUD_IN;
        INSERT INTO SUBASTA (ID_SOLICITUD, ID_ESTADO_SUBASTA, FECHA_PUBLICACION) VALUES (ID_SOLICITUD_IN, 1, SYSDATE);

    
        RAISE PRODUCTOR_PARTICIPATING;
        
    END IF;

EXCEPTION
    WHEN PRODUCTOR_PARTICIPATING THEN
        STATUS_RESULT_OUT:= 1;
        DBMS_OUTPUT.PUT_LINE('PRODUCTOR PARTICIPANDO CORRECTAMENTE' );
        COMMIT;
    WHEN REQUEST_NOT_FOUND THEN
        STATUS_RESULT_OUT:= 0;
        DBMS_OUTPUT.PUT_LINE('SOLICITUD NO ENCONTRADA' );
    WHEN PRODUCTOR_NOT_FOUND THEN
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('PRODUCTOR NO ENCONTRADO' );
    WHEN OTHERS THEN
        STATUS_RESULT_OUT:= -2;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END FV_PRO_REQUEST_PARTICIPATION;


--SET SERVEROUTPUT ON;   
--
--DECLARE
--STATUS_RESULT_OUT NUMBER;
--BEGIN
--    FV_PRO_REQUEST_PARTICIPATION(1,1,100,STATUS_RESULT_OUT);
--    DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);
--END;