
CREATE OR REPLACE FUNCTION FN_EJEMPLO1
(   
    VALOR NUMBER
)
RETURN NUMBER IS
BEGIN
    

--Declaración de Sentencia
    RETURN VALOR*2;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR EN LA FUNCTION ');
--Sentencias de control de excepción
END FN_EJEMPLO1;

SELECT EJEMPLO(5) AS RESULT FROM DUAL;