
CREATE OR REPLACE FUNCTION FN_EJEMPLO2
(   
    VALOR NUMBER
)
RETURN VARCHAR2 IS
    COSTO VARCHAR2(200);
BEGIN
    

--Declaración de Sentencia
    COSTO:='NEWVALOR';
  --  RETURN VALOR*2;
  RETURN COSTO;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR EN LA FUNCTION ');
--Sentencias de control de excepción
END FN_EJEMPLO2;

SELECT FN_EJEMPLO2(5) AS RESULT FROM DUAL;