
CREATE OR REPLACE FUNCTION FN_VALID_TRUCK
(   
    PATENTE_IN IN VARCHAR2,
    MODELO_IN IN VARCHAR2,
    MARCA_IN IN VARCHAR2,
    REVISION_TECNICA_IN IN NUMBER,
    DISPONIBILIDAD_IN IN NUMBER,
    ID_TIPO_CAMION_IN IN NUMBER,
    ID_TAMANO_CAMION_IN IN NUMBER
)
RETURN NUMBER AS
    INVALID_MODEL_TRUCK EXCEPTION;
    IS_VALID_MODEL_TRUCK EXCEPTION;
    STATUS_RESULT NUMBER;
BEGIN
    IF 
    PATENTE_IN IS NULL OR PATENTE_IN = '' OR
    MODELO_IN IS NULL OR MODELO_IN = '' OR
    MARCA_IN IS NULL OR MARCA_IN = '' OR
    REVISION_TECNICA_IN IS NULL OR REVISION_TECNICA_IN = 0 OR
    DISPONIBILIDAD_IN IS NULL OR DISPONIBILIDAD_IN = 0 OR
    DISPONIBILIDAD_IN IS NULL OR DISPONIBILIDAD_IN = 0 OR
    ID_TIPO_CAMION_IN IS NULL OR ID_TIPO_CAMION_IN = 0 OR
    ID_TAMANO_CAMION_IN IS NULL OR ID_TAMANO_CAMION_IN = 0 
    THEN
        RAISE INVALID_MODEL_TRUCK;
    ELSE
       RAISE IS_VALID_MODEL_TRUCK;
    END IF;
    
--Declaración de Sentencia
    RETURN STATUS_RESULT;
EXCEPTION
    WHEN INVALID_MODEL_TRUCK THEN
         STATUS_RESULT:=0;
         RETURN STATUS_RESULT;
    WHEN IS_VALID_MODEL_TRUCK THEN
         STATUS_RESULT:=1;
         RETURN STATUS_RESULT;
    WHEN OTHERS THEN
        STATUS_RESULT:=-1;
        RETURN STATUS_RESULT;
        DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR EN LA FUNCTION ');
--Sentencias de control de excepción
END FN_VALID_TRUCK;
