CREATE OR REPLACE PROCEDURE FV_LOGIN
 (
    CORREO_IN IN  VARCHAR2,
    CONTRASENA_IN IN  VARCHAR2,
    ID_TIPO_USUARIO_IN IN VARCHAR2,
    STATUS_OUT OUT NUMBER
   
)
AS
 ADMINISTRADOR BOOLEAN := FALSE;
 PRODUCTOR BOOLEAN := FALSE;
 CLIENTE BOOLEAN := FALSE;
 TRANSPORTISTA BOOLEAN := FALSE;
 CONSULTOR BOOLEAN := FALSE;
 COUNT_USER NUMBER := 0;
 
BEGIN
 


    IF ID_TIPO_USUARIO_IN NOT BETWEEN 1 AND 4 THEN
        STATUS_OUT:= 0;
    ELSE
        
        CASE ID_TIPO_USUARIO_IN 
            WHEN 1 THEN 
                ADMINISTRADOR := TRUE;
                DBMS_OUTPUT.PUT_LINE('ADMINISTRADOR');
            WHEN 2 THEN 
                PRODUCTOR := TRUE;
                DBMS_OUTPUT.PUT_LINE('PRODUCTOR');       
            WHEN 3 THEN
                CLIENTE := TRUE;
                DBMS_OUTPUT.PUT_LINE('CLIENTE');
            WHEN 4 THEN
                TRANSPORTISTA := TRUE;
                DBMS_OUTPUT.PUT_LINE('TRANSPORTISTA');
            WHEN 5 THEN
                CONSULTOR := TRUE;
                DBMS_OUTPUT.PUT_LINE('CONSULTOR');
        END CASE;
    END IF;

    IF ADMINISTRADOR = TRUE THEN
        SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
            IF  COUNT_USER > 0 THEN
                STATUS_OUT:= 1;
            END IF;
    ELSIF PRODUCTOR = TRUE THEN
        SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN ;
            IF COUNT_USER > 0 THEN
                STATUS_OUT:=1;
            END IF;
    ELSIF CLIENTE = TRUE THEN
        SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN ;
            IF COUNT_USER > 0 THEN
                STATUS_OUT:=1;
            END IF;
    ELSIF TRANSPORTISTA = TRUE THEN
            SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN ;
                IF COUNT_USER > 0 THEN
                    STATUS_OUT:=1;
                    NULL;
                END IF;
    ELSIF CONSULTOR = TRUE THEN
        SELECT COUNT(*) INTO COUNT_USER FROM USUARIO WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN ;
            IF COUNT_USER > 0 THEN
                STATUS_OUT:=1;
                NULL;
            END IF;
    END IF;

DBMS_OUTPUT.PUT_LINE('FG');

DBMS_OUTPUT.PUT_LINE('CORREO:' || CORREO_IN);
DBMS_OUTPUT.PUT_LINE('CONTRASENA_IN:' || CONTRASENA_IN);
DBMS_OUTPUT.PUT_LINE('ID_TIPO_USUARIO_IN:' || ID_TIPO_USUARIO_IN);
DBMS_OUTPUT.PUT_LINE('STATUS_OUT:' || STATUS_OUT);



EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('UP HUBO UN ERROR' );
   
END;

SET SERVEROUTPUT ON;


DECLARE 
     STATUS_OUT NUMBER;
BEGIN
    FV_LOGIN('luciano@gmaiil.com','aaa',1 , STATUS_OUT);
    DBMS_OUTPUT.PUT_LINE('STATUS_OUT WHEN EXECUTE:' ||STATUS_OUT);
    
END;
