create or replace PROCEDURE FV_TRA_UPDATE_TRUCK
 (
    PATENTE_IN IN VARCHAR2,
    MODELO_IN IN VARCHAR2,
    MARCA_IN IN VARCHAR2,
    REVISION_TECNICA_IN IN NUMBER,
    DISPONIBILIDAD_IN IN NUMBER,
    ID_TIPO_CAMION_IN IN NUMBER,
    ID_TAMANO_CAMION_IN IN NUMBER,
    ID_TRANSPORTISTA_IN IN NUMBER,
    ID_RESULT_OUT OUT NUMBER,
    STATUS_RESULT_OUT OUT NUMBER
    
)

AS 
    INVALID_MODEL EXCEPTION;
    ID_TEMP_VAR NUMBER := 0;
    TRUCK_EDITED EXCEPTION;
    TRUCK_NOT_FOUND EXCEPTION;
    COUNT_TRUCK NUMBER := 0;
    IS_VALID_TRUCK NUMBER  := 0;
BEGIN
    SELECT FN_VALID_TRUCK(PATENTE_IN, MODELO_IN, MARCA_IN, REVISION_TECNICA_IN, DISPONIBILIDAD_IN, ID_TIPO_CAMION_IN, ID_TAMANO_CAMION_IN) INTO IS_VALID_TRUCK FROM DUAL;   
    IF IS_VALID_TRUCK != 1 THEN
        DBMS_OUTPUT.PUT_LINE('HAY PROBLEMA CON LA FUNCION DEBIDO A QUE EL MODELO NO ESTA COMPLETO' );
        RAISE INVALID_MODEL;
    END IF;
--    
    SELECT COUNT(*) INTO COUNT_TRUCK FROM CAMION WHERE PATENTE = PATENTE_IN;
    IF  COUNT_TRUCK > 0 THEN
        SELECT ID_CAMION INTO ID_TEMP_VAR FROM CAMION WHERE PATENTE = PATENTE_IN;
        UPDATE CAMION SET PATENTE = PATENTE_IN, MODELO = MODELO_IN, MARCA = MARCA_IN, REVISION_TECNICA = REVISION_TECNICA_IN, DISPONIBILIDAD = DISPONIBILIDAD_IN, ID_TIPO_CAMION = ID_TIPO_CAMION_IN, 
        ID_TAMANO_CAMION = ID_TAMANO_CAMION_IN, ID_TRANSPORTISTA = ID_TRANSPORTISTA_IN WHERE ID_CAMION = ID_TEMP_VAR ;
        RAISE TRUCK_EDITED;
    END IF; 
    
    EXCEPTION
    WHEN TRUCK_EDITED THEN
        STATUS_RESULT_OUT := 1;
        DBMS_OUTPUT.PUT_LINE('CAMION EDITADO' );
    WHEN INVALID_MODEL THEN
        STATUS_RESULT_OUT := 0;
        DBMS_OUTPUT.PUT_LINE('MODELO INGRESADO INVALIDO' );
    WHEN OTHERS THEN   
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
        
END;


--DECLARE 
--    ID_RESULT_OUT NUMBER;
--    STATUS_RESULT_OUT NUMBER;
--BEGIN
--    FV_TRA_UPDATE_TRUCK('123CASD', '', 'NiSssan', 1, 1, 1, 1, 1, ID_RESULT_OUT, STATUS_RESULT_OUT);
--    DBMS_OUTPUT.PUT_LINE(ID_RESULT_OUT);
--END;
