CREATE OR REPLACE 
PROCEDURE FV_TRA_DELETE_TRUCK(
ID_CAMION_IN IN NUMBER
,STATUS_RESULT_OUT OUT NUMBER)

AS
TRUCK_DELETED EXCEPTION;
TRUCK_NOT_FOUND EXCEPTION;
COUNT_TRUCK NUMBER :=0;
BEGIN
    SELECT COUNT(*) INTO COUNT_TRUCK FROM CAMION WHERE ID_CAMION = ID_CAMION_IN;
    IF COUNT_TRUCK = 0 THEN
        RAISE TRUCK_NOT_FOUND;
    ELSE
        DELETE FROM CAMION WHERE ID_CAMION = ID_CAMION_IN;
        RAISE TRUCK_DELETED;
    END IF;
        
    

EXCEPTION
    WHEN TRUCK_NOT_FOUND THEN
        STATUS_RESULT_OUT:= 0;
        DBMS_OUTPUT.PUT_LINE('CAMION NO ENCONTRADO' );
    WHEN TRUCK_DELETED THEN
        STATUS_RESULT_OUT:= 1;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('CAMION ELIMINADO CORRECTAMENTE' );
    WHEN OTHERS THEN
        STATUS_RESULT_OUT:= -1;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END FV_TRA_DELETE_TRUCK;


-- SET SERVEROUTPUT ON;    
-- DECLARE
-- STATUS_RESULT_OUT NUMBER;
-- BEGIN
-- FV_TRA_DELETE_TRUCK(31,STATUS_RESULT_OUT);
-- DBMS_OUTPUT.PUT_LINE('STATUS_RESULT_OUT: '||STATUS_RESULT_OUT);
-- END;