create or replace PROCEDURE FV_TRA_AUCTION_PARTICIPATION
 (
    ID_SUBASTA_IN IN NUMBER,
    ID_CAMION_IN IN NUMBER,
    PRECIO_IN IN NUMBER,
    ID_RESULT_OUT OUT NUMBER,
    STATUS_RESULT_OUT OUT NUMBER
    
)

AS 
    TRUCK_COUNT NUMBER;
    AUCTION_COUNT NUMBER;
    COUNT_DT_AUCTION NUMBER;
    TRUCK_NOT_FOUND EXCEPTION;
    AUCTION_NOT_FOUND EXCEPTION;
    AUCTION_DT_FOUND EXCEPTION;

    AUCTION_PARTICIPATION_SUCCESS EXCEPTION;
    
BEGIN

    SELECT COUNT(*) INTO TRUCK_COUNT FROM CAMION WHERE ID_CAMION = ID_CAMION_IN AND DISPONIBILIDAD = 1;
    IF TRUCK_COUNT = 0 THEN
        RAISE TRUCK_NOT_FOUND;
    END IF;
    
    SELECT COUNT(*) INTO AUCTION_COUNT FROM SUBASTA WHERE ID_SUBASTA = ID_SUBASTA_IN;
    IF AUCTION_COUNT = 0 THEN
        RAISE AUCTION_NOT_FOUND;
    END IF;
    
    SELECT COUNT(*)INTO COUNT_DT_AUCTION FROM DETALLE_SUBASTA WHERE ID_SUBASTA = ID_SUBASTA_IN AND ID_CAMION = ID_CAMION_IN;
    IF COUNT_DT_AUCTION != 0 THEN
        RAISE AUCTION_DT_FOUND;
    END IF;
    
    INSERT INTO DETALLE_SUBASTA (ID_SUBASTA, ID_CAMION, PRECIO) VALUES (ID_SUBASTA_IN, ID_CAMION_IN, PRECIO_IN) RETURN ID_SUBASTA INTO ID_RESULT_OUT;
    UPDATE SUBASTA SET FECHA_TERMINO = SYSDATE, CAMION_SELECCIONADO = ID_CAMION_IN, ID_ESTADO_SUBASTA = 2 WHERE ID_SUBASTA = ID_SUBASTA_IN;
    RAISE AUCTION_PARTICIPATION_SUCCESS;
    
    EXCEPTION
    WHEN AUCTION_PARTICIPATION_SUCCESS THEN
        STATUS_RESULT_OUT := 1;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('DETALLE SUBASTA CREADA' );
    WHEN TRUCK_NOT_FOUND THEN
        STATUS_RESULT_OUT := 0;
        DBMS_OUTPUT.PUT_LINE('CAMION INGRESADO NO EXISTE' );
    WHEN AUCTION_NOT_FOUND THEN
        STATUS_RESULT_OUT := -1;
        DBMS_OUTPUT.PUT_LINE('SUBASTA INGRESADA NO EXISTE' );        
    WHEN AUCTION_DT_FOUND THEN
        STATUS_RESULT_OUT := -2;
        DBMS_OUTPUT.PUT_LINE('SUBASTA PREVIAMENTE INGRESADA' );  
    WHEN OTHERS THEN   
        STATUS_RESULT_OUT:= -3;
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
        
END;



-- DECLARE 
--     ID_RESULT_OUT NUMBER;
--     STATUS_RESULT_OUT NUMBER;
-- BEGIN
--     FV_TRA_AUCTION_PARTICIPATION(1, 2, 23233, ID_RESULT_OUT, STATUS_RESULT_OUT);
--     DBMS_OUTPUT.PUT_LINE(ID_RESULT_OUT);
--     DBMS_OUTPUT.PUT_LINE(STATUS_RESULT_OUT);

-- END;
