
CREATE OR REPLACE FUNCTION FN_VALID_USER
(   
    ID_PAIS_IN  NUMBER,
    NOMBRE_IN  VARCHAR2,
    APELLIDO_PATERNO_IN  VARCHAR2,
    APELLIDO_MATERNO_IN IN VARCHAR2,
    CORREO_IN IN VARCHAR2,
    CONTRASENA_IN IN VARCHAR2,
    RUT_IN IN NUMBER,
    NUMER_IDENTIFICADOR_IN IN VARCHAR2,
    DIRECCION_IN IN VARCHAR2,
    CODIGO_POSTAL_IN IN NUMBER,
    TELEFONO_IN IN NUMBER
)
RETURN NUMBER AS
    INVALID_MODEL_USER EXCEPTION;
    IS_VALID_MODEL_USER EXCEPTION;
    STATUS_RESULT NUMBER;
BEGIN
    IF 
    ID_PAIS_IN IS NULL OR ID_PAIS_IN = 0 OR 
    NOMBRE_IN IS NULL OR NOMBRE_IN = '' OR
    APELLIDO_MATERNO_IN IS NULL OR APELLIDO_MATERNO_IN = ''  OR
    APELLIDO_PATERNO_IN IS NULL OR APELLIDO_PATERNO_IN = ''  OR
    CORREO_IN IS NULL OR CORREO_IN = '' OR
    CONTRASENA_IN IS NULL OR CONTRASENA_IN = '' OR 
    RUT_IN IS NULL OR RUT_IN = 0 OR
    NUMER_IDENTIFICADOR_IN IS NULL OR NUMER_IDENTIFICADOR_IN = '' OR
    DIRECCION_IN IS NULL OR DIRECCION_IN = '' OR
    CODIGO_POSTAL_IN IS NULL OR CODIGO_POSTAL_IN = 0 OR
    TELEFONO_IN IS NULL OR TELEFONO_IN = 0 
    THEN
        RAISE INVALID_MODEL_USER;
    ELSE
       RAISE IS_VALID_MODEL_USER;
    END IF;
    
--Declaración de Sentencia
    RETURN STATUS_RESULT;
EXCEPTION
    WHEN INVALID_MODEL_USER THEN
         STATUS_RESULT:=0;
         RETURN STATUS_RESULT;
    WHEN IS_VALID_MODEL_USER THEN
         STATUS_RESULT:=1;
         RETURN STATUS_RESULT;
    WHEN OTHERS THEN
        STATUS_RESULT:=-1;
        RETURN STATUS_RESULT;
        DBMS_OUTPUT.PUT_LINE('OCURRIO UN ERROR EN LA FUNCTION ');
--Sentencias de control de excepción
END FN_VALID_USER;


-- EJECUCION
-- SELECT  FN_VALID_USER(1,'nuevoAdmin','DF','nuevoApellido', 'transportista@transportista.com','nuevoadmin',12345678,'k','Rencas 1673', 80001, 94986612) AS RESULT FROM DUAL;
