CREATE OR REPLACE PROCEDURE FV_LOGIN
 (
    CORREO_IN IN  VARCHAR2,
    CONTRASENA_IN IN  VARCHAR2,
    ID_TIPO_USUARIO_IN IN VARCHAR2,
    STATUS_OUT OUT NUMBER, 
    TIPO_USUARIO_OUT OUT VARCHAR2
)
AS
 ADMINISTRADOR BOOLEAN := FALSE;
 PRODUCTOR BOOLEAN := FALSE;
 CLIENTE BOOLEAN := FALSE;
 TRANSPORTISTA BOOLEAN := FALSE;
 CONSULTOR BOOLEAN := FALSE;
 COUNT_USER NUMBER := 0;
 NOM_TIPO_USUARIO VARCHAR2(20) :='';

BEGIN
    IF ID_TIPO_USUARIO_IN NOT BETWEEN 1 AND 6 THEN
        STATUS_OUT:= 0;
    ELSE       
        CASE ID_TIPO_USUARIO_IN 
            WHEN 1 THEN 
                ADMINISTRADOR := TRUE;
                DBMS_OUTPUT.PUT_LINE('ADMINISTRADOR');
                SELECT COUNT(*), TU.CATEGORIA INTO COUNT_USER, NOM_TIPO_USUARIO FROM USUARIO U JOIN TIPO_USUARIO TU ON (U.ID_USUARIO = TU.ID_TIPO_USUARIO) 
                WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN GROUP BY TU.CATEGORIA ;
                    IF  COUNT_USER > 0 THEN
                        STATUS_OUT:= 1;
                        TIPO_USUARIO_OUT:= NOM_TIPO_USUARIO;
                    END IF;
            WHEN 2 THEN
                CLIENTE := TRUE;
                DBMS_OUTPUT.PUT_LINE('CLIENTE');
                SELECT COUNT(*), TU.CATEGORIA INTO COUNT_USER, NOM_TIPO_USUARIO FROM USUARIO U JOIN TIPO_USUARIO TU ON (U.ID_USUARIO = TU.ID_TIPO_USUARIO) 
                WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN GROUP BY TU.CATEGORIA ;
                    IF COUNT_USER > 0 THEN
                        STATUS_OUT:=1;
                        TIPO_USUARIO_OUT:= NOM_TIPO_USUARIO;
                    END IF;
            WHEN 4 THEN
                CONSULTOR := TRUE;
                DBMS_OUTPUT.PUT_LINE('CONSULTOR');
                SELECT COUNT(*), TU.CATEGORIA INTO COUNT_USER, NOM_TIPO_USUARIO FROM USUARIO U JOIN TIPO_USUARIO TU ON (U.ID_USUARIO = TU.ID_TIPO_USUARIO) 
                WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN GROUP BY TU.CATEGORIA ;
                    IF COUNT_USER > 0 THEN
                        STATUS_OUT:=1;
                        TIPO_USUARIO_OUT:= NOM_TIPO_USUARIO;
                    END IF;
            WHEN 5 THEN 
                PRODUCTOR := TRUE;
                DBMS_OUTPUT.PUT_LINE('PRODUCTOR');
                SELECT COUNT(*) INTO COUNT_USER FROM PRODUCTOR 
                WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
                    IF COUNT_USER > 0 THEN
                        STATUS_OUT:=1;
                        TIPO_USUARIO_OUT:= 'PRODUCTOR';
                    END IF;
            WHEN 6 THEN
                TRANSPORTISTA := TRUE;
                DBMS_OUTPUT.PUT_LINE('TRANSPORTISTA');
                SELECT COUNT(*) INTO COUNT_USER FROM TRANSPORTISTA 
                WHERE CORREO = CORREO_IN AND CONTRASENA = CONTRASENA_IN;
                    IF COUNT_USER > 0 THEN
                        STATUS_OUT:=1;
                        TIPO_USUARIO_OUT:= 'TRANSPORTISTA';
                    END IF;
        END CASE;
    END IF;

DBMS_OUTPUT.PUT_LINE('FG');
DBMS_OUTPUT.PUT_LINE('CORREO:' || CORREO_IN);
DBMS_OUTPUT.PUT_LINE('CONTRASENA_IN:' || CONTRASENA_IN);
DBMS_OUTPUT.PUT_LINE('ID_TIPO_USUARIO_IN:' || ID_TIPO_USUARIO_IN);
DBMS_OUTPUT.PUT_LINE('STATUS_OUT:' || STATUS_OUT);
DBMS_OUTPUT.PUT_LINE('TIPO_USUARIO_OUT:' || TIPO_USUARIO_OUT);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END;

SET SERVEROUTPUT ON;


DECLARE 
     STATUS_OUT NUMBER;
     TIPO_USUARIO_OUT VARCHAR2(20);
BEGIN
    FV_LOGIN('productor@productor.com','123asd',5 , STATUS_OUT, TIPO_USUARIO_OUT);
    DBMS_OUTPUT.PUT_LINE('STATUS_OUT WHEN EXECUTE:' ||STATUS_OUT ||TIPO_USUARIO_OUT);
    
END;