CREATE OR REPLACE PROCEDURE FV_CREATE_PURCHASE_REQUEST (
    ID_USUARIO_IN IN NUMBER,
    ID_TIPO_SOLICITUD_IN IN NUMBER,
    KILOS_IN IN NUMBER,
    ID_FRUTA_IN IN NUMBER,
    CALIDAD_IN IN NUMBER,
    CATEGORIA_IN IN NUMBER,
    ID_REQUEST_RESULT_OUT OUT NUMBER,
    ID_REQUEST_DETAIL_RESULT_OUT OUT NUMBER,
    STATUS_RESULT_OUT OUT NUMBER
)
AS
    INVALID_MODEL EXCEPTION;
    REQUEST_CREATED EXCEPTION;
    IS_VALID_REQUEST NUMBER := 0;
    ID_REQUEST_VAL NUMBER := 0;
    ID_DETAIL_REQUEST_VAL NUMBER := 0;
BEGIN

    SELECT FN_VALID_REQUEST(ID_USUARIO_IN, ID_TIPO_SOLICITUD_IN, KILOS_IN, ID_FRUTA_IN, CALIDAD_IN, CATEGORIA_IN) INTO IS_VALID_REQUEST FROM DUAL;
    IF IS_VALID_REQUEST != 1 THEN
            DBMS_OUTPUT.PUT_LINE('HAY PROBLEMA CON LA FUNCION DEBIDO A QUE EL MODELO NO ESTA COMPLETO' );
            RAISE INVALID_MODEL;
    END IF;

    INSERT INTO SOLICITUD (ID_USUARIO, ID_TIPO_SOLICITUD, ID_ESTADO_SOLICITUD, PRODUCTOR_SELECCIONADO, FECHA_PUBLICACION) VALUES (ID_USUARIO_IN, ID_TIPO_SOLICITUD_IN, 0, null, sysdate) RETURN ID_SOLICITUD INTO ID_REQUEST_VAL;
    INSERT INTO DETALLE_SOLICITUD (ID_SOLICITUD, ID_FRUTA, ID_CALIDAD, KILOS) VALUES (ID_REQUEST_VAL, ID_FRUTA_IN, CALIDAD_IN, KILOS_IN) RETURN ID_DETALLE_SOLICITUD INTO ID_DETAIL_REQUEST_VAL;
    RAISE REQUEST_CREATED;

EXCEPTION
    WHEN REQUEST_CREATED THEN
    ID_REQUEST_RESULT_OUT:= ID_REQUEST_VAL;
    ID_REQUEST_DETAIL_RESULT_OUT:= ID_DETAIL_REQUEST_VAL;
    STATUS_RESULT_OUT:= 1;
    
    DBMS_OUTPUT.PUT_LINE('SOLICITUD CREADA' );
    WHEN INVALID_MODEL THEN
    STATUS_RESULT_OUT:= -1;
    DBMS_OUTPUT.PUT_LINE('MODELO INVALIDO' );
    WHEN OTHERS THEN 
    STATUS_RESULT_OUT:= 0;
    DBMS_OUTPUT.PUT_LINE('UPS HUBO UN ERROR' );
END;

    
    
    